/**
 * autoresearch.ts
 *
 * Learned on-demand from: https://github.com/karpathy/autoresearch
 * Why: Andrej Karpathy's autonomous research agent. Self-directed learning and hypothesis testing loop for AI research.
 *
 * MINIMAL SLICE: "A minimal autoresearch skill: /research command that takes a research question, performs iterative web search + reasoning, generates hypotheses, and validates against sources."
 */

export const autoresearch = {
  name: "autoresearch",
  description: "Andrej Karpathy's autonomous research agent. Self-directed learning and hypothesis testing loop for AI research.",
  aliases: [],
  async execute(args: string, context: SkillContext): Promise<SkillResult> {
    // TODO: Implement autoresearch capability
    // Minimal slice: "A minimal autoresearch skill: /research command that takes a research question, performs iterative ...

    return {
      content: `🎯 autoresearch skill - implemented on-demand

Your intent was interpreted as: ${args}

This capability was learned from: https://github.com/karpathy/autoresearch

The core technique: Andrej Karpathy's autonomous research agent. Self-directed learning and hypothesis testing loop for AI research.

To complete implementation:
1. Run: bun run src/tools/harvest.ts --once
2. Check the source repo for full implementation
3. Complete the TODO sections below`,
    };
  },
};

// Auto-generated by on-demand-learner.ts
import type { Skill, SkillContext, SkillResult } from "./loader.ts";
