#!/usr/bin/env python3
"""compact.py — the forgetting function + playbook generator.

1. Regenerates .meow/playbook.md FROM brain.db (collection 'playbook').
   playbook.md is a build artifact — the brain is the single source of truth.
2. Archives ledger body beyond the last 30 entries to .meow/archive/.
Safe to run anytime; idempotent.
"""
import datetime
import shutil
import sqlite3
import sys
import tempfile
from pathlib import Path

MEOW = Path(__file__).resolve().parent.parent / ".meow"
HEADER = ("# playbook — promoted rules (GENERATED by scripts/compact.py)\n"
          "<!-- Do not hand-edit. Source of truth: .meow/brain.db, collection 'playbook'. -->\n"
          "<!-- Injected whole into every birth prompt. Keep it small, true, load-bearing. -->\n\n")


def _query_rules(db: Path):
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        return con.execute(
            "SELECT title, content FROM drawers "
            "WHERE collection='playbook' AND deleted_at IS NULL "
            "ORDER BY updated_at DESC").fetchall()
    finally:
        con.close()


def regen_playbook() -> str:
    db = MEOW / "brain.db"
    rules = []
    if db.exists():
        try:
            rows = _query_rules(db)
        except sqlite3.Error:
            # WAL/readonly-mount edge: read from a temp copy instead.
            try:
                with tempfile.TemporaryDirectory() as td:
                    tmp = Path(td) / "brain.db"
                    shutil.copy(db, tmp)
                    rows = _query_rules(tmp)
            except (sqlite3.Error, OSError) as e:
                return f"playbook: brain unreadable ({e}) — left untouched"
        rules = [f"- **{t}** — {c.strip()}" for t, c in rows]
    body = HEADER + ("\n".join(rules) + "\n" if rules else
                     "_No promoted rules yet. Candidates live in the brain; "
                     "promotion needs two cited observations or a proving verifier._\n")
    (MEOW / "playbook.md").write_text(body, encoding="utf-8")
    return f"playbook: regenerated with {len(rules)} promoted rule(s)"


def compact_ledger(keep: int = 30) -> str:
    ledger = MEOW / "ledger.md"
    if not ledger.exists():
        return "ledger: none"
    lines = ledger.read_text(encoding="utf-8").splitlines()
    entries = [i for i, ln in enumerate(lines) if ln.strip().startswith("- ")]
    if len(entries) <= keep:
        return f"ledger: {len(entries)} entries, no compaction needed"
    cut = entries[-keep]
    head_meta = [ln for ln in lines[:entries[0]]]
    old, live = lines[entries[0]:cut], lines[cut:]
    stamp = datetime.date.today().isoformat()
    (MEOW / "archive" / f"ledger-{stamp}.md").write_text(
        "\n".join(old) + "\n", encoding="utf-8")
    ledger.write_text("\n".join(head_meta + live) + "\n", encoding="utf-8")
    return f"ledger: archived {len(old)} lines, kept {keep} entries"


def main() -> int:
    print(regen_playbook())
    print(compact_ledger())
    return 0


if __name__ == "__main__":
    sys.exit(main())
